# Generated by Django 2.2.3 on 2023-07-22 02:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('creditcards', '0002_installment_transaction'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='installments',
            new_name='installment',
        ),
    ]
