# Generated by Django 2.2.3 on 2023-07-22 02:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('creditcards', '0003_auto_20230722_0207'),
    ]

    operations = [
        migrations.AddField(
            model_name='installment',
            name='card',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='creditcards.CreditCard'),
            preserve_default=False,
        ),
    ]
