# Generated by Django 2.2.3 on 2019-08-01 03:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('ahorro', 'Caja de Ahorro'), ('corriente', 'Cuenta Coriente'), ('efete', 'Efectivo'), ('digital', 'Billetera digital'), ('plazo', 'Plazo fijo')], max_length=10)),
                ('alias', models.CharField(max_length=30)),
                ('entity', models.CharField(blank=True, max_length=30, null=True)),
                ('cbu_cvu', models.PositiveIntegerField(blank=True, null=True, verbose_name='CBU/CVU')),
                ('external_id', models.CharField(blank=True, max_length=300, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['alias'],
            },
        ),
    ]
